FEATURE_NAMES = [
    "node_count",
    "rel_count",
    "triple_count",
    "type_triple_count",
    "has_type",
    "component_count",
    "has_disconnected",
    "invalid_predicate_count",
    "unused_select_vars",
    "distinct_label_count",
    "distinct_relation_count",
    "has_variable_length",
    "has_optional",
    "has_where",
    "has_exists",
    "has_distinct",
    "has_aggregation",
    "property_filter_count",
    "entity_coverage",
    "entity_precision",
    "relation_coverage",
    "relation_precision",
    "expected_intermediate_coverage",
    "unexpected_label_ratio",
    "predicate_overlap",
    "class_overlap",
    "missing_predicates",
    "extra_predicates",
    # Infineon-specific [7]
    "has_named_instance",
    "uses_correct_survey",
    "semantic_similarity",

]
